name: "HDF5 DataLogger"
version: "0.2.17"
slug: "hdf5_datalogger"
description: "Logs selected Home Assistant states using REST API and saves them to a report file."
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
homeassistant_api: true
apparmor: true

map:
  - share:rw

options:
  update_interval: 60
  output_path: "/share/example_addon_output.txt"
  max_entities: 0

  # Se vuoto: usiamo i domini di default
  # (sensor, binary_sensor, button, climate, light)
  include_domains: []

schema:
  update_interval: int
  output_path: str
  max_entities: int

  include_domains:
    - str
